name: Deploy to Juno

on:
    release:
        types: [released]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: '9.x'
                  run_install: |
                      args: [--global, vercel]

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Create pnpm store directory if needed
              run: mkdir -p ~/.pnpm-store

            - name: Cache pnpm store
              uses: actions/cache@v4
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
              restore-keys: |
                  ${{ runner.os }}-pnpm-

            - name: Build
              run: pnpm run build

            - name: Deploy to Juno
              uses: junobuild/juno-action@main
              with:
                  args: deploy
              env:
                  JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
